
surface.CreateFont("LoupGG_countdown", {
  font = "Arial", 
  extended = false,
  size = 75,
  weight = 500,
  blursize = 0,
  scanlines = 0,
  antialias = true,
  underline = false,
  italic = false,
  strikeout = false,
  symbol = false,
  rotary = false,
  shadow = true,
  additive = false,
  outline = false,
})

surface.CreateFont("LoupGG_tag", {
  font = "Arial", 
  extended = false,
  size = 21,
  weight = 2000,
  blursize = 0,
  scanlines = 0,
  antialias = true,
  underline = false,
  italic = false,
  strikeout = false,
  symbol = false,
  rotary = false,
  shadow = true,
  additive = false,
  outline = false,
})
